language: rust
dist: trusty
sudo: required
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
  - rust: nightly
  - rust: beta
  fast_finish: true
  exclude:
    - rust: nightly
    - rust: beta
  include:
    - rust: nightly
      env: FEATURES="ceph gluster vault"
    - rust: beta
      env: FEATURES="ceph gluster vault"
env:
  - FEATURES="ceph"
  - FEATURES="gluster"
  - FEATURES="vault"
  - FEATURES="ceph gluster"
  - FEATURES="ceph vault"
  - FEATURES="gluster vault"
  - FEATURES="ceph gluster vault"
before_install:
  - sudo add-apt-repository ppa:gluster/glusterfs-3.8 -y
  - sudo add-apt-repository cloud-archive:mitaka -y
  - sudo apt-get update -q
  - sudo apt-get install glusterfs-common
  - sudo apt-get install librados-dev
addons:
  apt:
    packages:
      - liblzma-dev
script:
  - cargo build --features$FEATURES --verbose
  - cargo test --features=$FEATURES --verbose
