language: rust
dist: trusty
sudo: required
env:
  - FEATURES="ceph"
  - FEATURES="gluster"
  - FEATURES="vault"
  - FEATURES="ceph gluster"
  - FEATURES="ceph vault"
  - FEATURES="gluster vault"
  - FEATURES="ceph gluster vault"
rust:
  - stable
  - beta
before_install:
  - sudo add-apt-repository ppa:gluster/glusterfs-3.8 -y
  - sudo add-apt-repository cloud-archive:mitaka -y
  - sudo apt-get update -q
  - sudo apt-get install glusterfs-common
  - sudo apt-get install librados-dev
addons:
  apt:
    packages:
      - liblzma-dev
      - unzip
script:
  - cargo build --features$FEATURES --verbose
  - cargo test --features=$FEATURES --verbose
