[package]
name = "preserve"
version = "0.1.0"
authors = ["fpgaminer <fpgaminer@bitcoin-mining.com>"]
description = "Encrypted backup system."
repository = "https://github.com/fpgaminer/preserve"
readme = "README.md"
license = "MIT OR Apache-2.0"

[dependencies]
rustc-serialize = "^0.3"
rust-crypto = "^0.2"
rand = "^0.3"
getopts = "^0.2"
rust-lzma = "^0.2"
libc = "^0.2"
rust-acd = { path = "rust-acd" }
tempdir = "^0.3"
rusqlite = "^0.6"

[profile.dev]
opt-level = 2
debug = true
